site_name: Ktor Swagger UI
site_url: https://smiley4.github.io/ktor-swagger-ui
repo_name: ktor-swagger-ui
repo_url: https://github.com/SMILEY4/ktor-swagger-ui
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: ['examples/src/main/kotlin/io/github/smiley4/ktoropenapi/examples']
      dedent_subsections: True
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
#  - pymdownx.blocks.caption

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
#  anchors: warn

nav:
  - Getting Started:
      - Introduction: index.md
      - Installation: installation.md
      - Quickstart: quickstart.md
  - User Guide:
#      - Configuration:
#          - OpenAPI: user-guide/configuration/openapi.md
#          - Swagger UI: user-guide/configuration/swagger-ui.md
#          - ReDoc: user-guide/configuration/redoc.md
      - Documenting Routes:
          - Basic Information: user-guide/documenting-routes/basic-information.md
          - Types and Schemas: user-guide/documenting-routes/types-and-schemas.md
          - Customizing Schema Generation: user-guide/documenting-routes/customizing-schema-generation.md
          - Customizing OpenAPI Examples: user-guide/documenting-routes/customizing-openapi-examples.md
      - Multiple API Specs: user-guide/multiple-api-specs.md
  - Examples:
      - Basics: examples/basics.md
      - Minimal: examples/minimal.md
      - Complete Configuration: examples/complete-configuration.md
      - Schemas: examples/schemas.md
      - Customized Schema Generator: examples/customized-schema-generator.md
      - Requests and Responses: examples/request-response.md
      - Authentication: examples/authentication.md
      - Petstore: examples/petstore.md
      - OpenAPI Examples: examples/openapi-examples.md
      - Multiple Specs: examples/multiple-specs.md
      - External OpenAPI Spec: examples/external-openapi-spec.md
      - Kotlinx Serialization: examples/kotlinx-serialization.md
      - File Upload: examples/file-upload.md
  - API Reference:
      - ktor-openapi: dokka/ktor-openapi/index.md
      - ktor-swagger-ui: dokka/ktor-swagger-ui/index.md
      - ktor-redoc: dokka/ktor-redoc/index.md
  - Migration Guide: migration-guide.md
  - Changelog: changelog.md
